import { Game, ChatMessage, OnlineStats, Bet } from '@/types';

export const originalsGames: Game[] = [
  {
    id: '1',
    name: 'Dice',
    slug: 'dice',
    category: 'originals',
    rtp: 100,
    image: '/images/games/dice.jpg',
  },
  {
    id: '2',
    name: 'Blackjack',
    slug: 'blackjack',
    category: 'originals',
    rtp: 100,
    image: '/images/games/blackjack.jpg',
  },
  {
    id: '3',
    name: 'Plinko',
    slug: 'plinko',
    category: 'originals',
    rtp: 100,
    image: '/images/games/plinko.jpg',
  },
  {
    id: '4',
    name: 'Crash',
    slug: 'crash',
    category: 'originals',
    rtp: 100,
    image: '/images/games/crash.jpg',
  },
  {
    id: '5',
    name: 'Mines',
    slug: 'mines',
    category: 'originals',
    rtp: 100,
    image: '/images/games/mines.jpg',
  },
  {
    id: '6',
    name: 'Beef',
    slug: 'beef',
    category: 'originals',
    rtp: 99.2,
    image: '/images/games/beef.jpg',
  },
  {
    id: '7',
    name: 'Keno',
    slug: 'keno',
    category: 'originals',
    rtp: 100,
    image: '/images/games/keno.jpg',
  },
  {
    id: '8',
    name: 'Castle Roulette',
    slug: 'castle-roulette',
    category: 'originals',
    rtp: 100,
    isLive: true,
    image: '/images/games/castle-roulette.jpg',
  },
];

export const casinoGames: Game[] = [
  {
    id: 'c1',
    name: 'Majestic Meow',
    slug: 'avatarux_majestic_meow',
    category: 'casino',
    rtp: 96,
    image: '/images/games/majestic-meow.webp',
    provider: 'AvatarUX',
  },
  {
    id: 'c2',
    name: 'AviaMasters',
    slug: 'bgaming_aviamasters',
    category: 'casino',
    rtp: 97,
    image: '/images/games/aviamasters.webp',
    provider: 'BGaming',
  },
  {
    id: 'c3',
    name: 'Bonanza Billion',
    slug: 'bgaming_bonanza_billion',
    category: 'casino',
    rtp: 96,
    image: '/images/games/bonanza-billion.webp',
    provider: 'BGaming',
  },
  {
    id: 'c4',
    name: 'Merge Up 2',
    slug: 'bgaming_merge_up_2',
    category: 'casino',
    rtp: 96,
    image: '/images/games/merge-up-2.webp',
    provider: 'BGaming',
  },
  {
    id: 'c5',
    name: 'Banana Farm',
    slug: 'backseat_gaming_banana_farm',
    category: 'casino',
    rtp: 96,
    image: '/images/games/banana-farm.webp',
    provider: 'Backseat Gaming',
  },
  {
    id: 'c6',
    name: 'Snoop Dogg Dollars',
    slug: 'bgaming_snoop_dogg_dollars',
    category: 'casino',
    rtp: 96,
    image: '/images/games/snoop-dogg-dollars.webp',
    provider: 'BGaming',
  },
  {
    id: 'c7',
    name: 'Aztec Clusters',
    slug: 'bgaming_aztec_clusters',
    category: 'casino',
    rtp: 96,
    image: '/images/games/aztec-clusters.webp',
    provider: 'BGaming',
  },
  {
    id: 'c8',
    name: 'Gold Rush - Johnny Cash',
    slug: 'bgaming_gold_rush_johnny_cash',
    category: 'casino',
    rtp: 96,
    image: '/images/games/gold-rush-johnny-cash.webp',
    provider: 'BGaming',
  },
  {
    id: 'c9',
    name: 'Pyrofox',
    slug: 'backseat_gaming_pyrofox',
    category: 'casino',
    rtp: 96,
    image: '/images/games/pyrofox.webp',
    provider: 'Backseat Gaming',
  },
  {
    id: 'c10',
    name: 'Pirate Bonanza',
    slug: 'backseat_gaming_pirate_bonanza',
    category: 'casino',
    rtp: 96,
    image: '/images/games/pirate-bonanza.webp',
    provider: 'Backseat Gaming',
  },
  {
    id: 'c11',
    name: 'European Roulette',
    slug: 'bgaming_european_roulette',
    category: 'casino',
    rtp: 97.3,
    image: '/images/games/european-roulette.webp',
    provider: 'BGaming',
  },
  {
    id: 'c12',
    name: 'Chocolate Rocket',
    slug: 'backseat_gaming_chocolate_rocket',
    category: 'casino',
    rtp: 96,
    image: '/images/games/chocolate-rocket.webp',
    provider: 'Backseat Gaming',
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    username: 'Arturian',
    message: 'feels bad man',
    timestamp: Date.now() - 60000,
  },
  {
    id: '2',
    username: 'Brucey',
    message: "There's still time bro",
    timestamp: Date.now() - 55000,
  },
  {
    id: '3',
    username: 'Nicot1ne',
    message: "im tellin u, its basketball, anything can happen",
    timestamp: Date.now() - 50000,
    isMod: true,
  },
  {
    id: '4',
    username: 'Yoyokas',
    message: 'nico is a NBA professional gamba',
    timestamp: Date.now() - 45000,
  },
  {
    id: '5',
    username: 'ChristianLoses',
    message: "Who's gonna win",
    timestamp: Date.now() - 40000,
  },
  {
    id: '6',
    username: 'fuckoff',
    message: '89:89 wtfff',
    timestamp: Date.now() - 35000,
  },
  {
    id: '7',
    username: 'Brucey',
    message: 'Hahahaha its so close',
    timestamp: Date.now() - 30000,
  },
  {
    id: '8',
    username: 'ChristianLoses',
    message: 'No stress at all',
    timestamp: Date.now() - 25000,
  },
  {
    id: '9',
    username: 'Yoyokas',
    message: 'cmonn',
    timestamp: Date.now() - 20000,
  },
  {
    id: '10',
    username: 'fuckoff',
    message: 'yesss 93',
    timestamp: Date.now() - 15000,
  },
];

export const mockOnlineStats: OnlineStats = {
  count: 652,
  announcement: '$1m monthly and $30k daily leaderboards now live. All slots, live games and Beef are included.',
};

export const mockBets: Bet[] = [
  {
    id: '28692490',
    game: 'Dice',
    gameIcon: 'dice',
    player: 'AlightAflame',
    wager: 0.01,
    currency: 'usdc',
    multiplier: 2,
    payout: 0.02,
    timestamp: Date.now() - 1000,
  },
  {
    id: '206340182',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'dad12',
    wager: 0.25,
    currency: 'duel',
    multiplier: 2.8,
    payout: 0.70,
    timestamp: Date.now() - 2000,
  },
  {
    id: '206340104',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'Daking4300',
    wager: 0.30,
    currency: 'usdt',
    multiplier: 0,
    payout: null,
    timestamp: Date.now() - 3000,
  },
  {
    id: '8174527',
    game: 'Blackjack',
    gameIcon: 'blackjack',
    player: 'OnnaComeUp',
    wager: 18.29,
    currency: 'sol',
    multiplier: 2,
    payout: 36.58,
    timestamp: Date.now() - 4000,
  },
  {
    id: '206340086',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'PaulDoWin',
    wager: 14.99,
    currency: 'sol',
    multiplier: 0,
    payout: null,
    timestamp: Date.now() - 5000,
  },
  {
    id: '28692473',
    game: 'Dice',
    gameIcon: 'dice',
    player: 'Steve25m',
    wager: 0.02,
    currency: 'eth',
    multiplier: 2,
    payout: 0.04,
    timestamp: Date.now() - 6000,
  },
  {
    id: '8174524',
    game: 'Blackjack',
    gameIcon: 'blackjack',
    player: 'dtrav9571',
    wager: 20.00,
    currency: 'usdt',
    multiplier: 1,
    payout: 20.00,
    timestamp: Date.now() - 7000,
  },
  {
    id: '206340093',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'woezi',
    wager: 17.98,
    currency: 'sol',
    multiplier: 0.15,
    payout: 2.74,
    timestamp: Date.now() - 8000,
  },
  {
    id: '206340019',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'pulga',
    wager: 0.74,
    currency: 'xrp',
    multiplier: 0,
    payout: null,
    timestamp: Date.now() - 9000,
  },
  {
    id: '28692461',
    game: 'Dice',
    gameIcon: 'dice',
    player: 'nard',
    wager: 2.00,
    currency: 'ltc',
    multiplier: 0,
    payout: null,
    timestamp: Date.now() - 10000,
  },
];

export const mockHighRollerBets: Bet[] = [
  {
    id: '28692500',
    game: 'Blackjack',
    gameIcon: 'blackjack',
    player: 'WhaleKing',
    wager: 5000.00,
    currency: 'usdc',
    multiplier: 2,
    payout: 10000.00,
    timestamp: Date.now() - 1000,
  },
  {
    id: '28692501',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'BigMoney99',
    wager: 2500.00,
    currency: 'sol',
    multiplier: 1.5,
    payout: 3750.00,
    timestamp: Date.now() - 2000,
  },
  {
    id: '28692502',
    game: 'Dice',
    gameIcon: 'dice',
    player: 'CryptoLord',
    wager: 1800.00,
    currency: 'eth',
    multiplier: 3,
    payout: 5400.00,
    timestamp: Date.now() - 3000,
  },
  {
    id: '28692503',
    game: 'Crash',
    gameIcon: 'crash',
    player: 'DiamondHands',
    wager: 3200.00,
    currency: 'usdt',
    multiplier: 0,
    payout: null,
    timestamp: Date.now() - 4000,
  },
  {
    id: '28692504',
    game: 'Blackjack',
    gameIcon: 'blackjack',
    player: 'VIPplayer',
    wager: 4500.00,
    currency: 'usdc',
    multiplier: 2.5,
    payout: 11250.00,
    timestamp: Date.now() - 5000,
  },
  {
    id: '28692505',
    game: 'Casino',
    gameIcon: 'casino',
    player: 'HighStakes',
    wager: 2000.00,
    currency: 'sol',
    multiplier: 0.5,
    payout: 1000.00,
    timestamp: Date.now() - 6000,
  },
  {
    id: '28692506',
    game: 'Plinko',
    gameIcon: 'plinko',
    player: 'MoonShot',
    wager: 1500.00,
    currency: 'eth',
    multiplier: 10,
    payout: 15000.00,
    timestamp: Date.now() - 7000,
  },
  {
    id: '28692507',
    game: 'Mines',
    gameIcon: 'mines',
    player: 'RiskTaker',
    wager: 3000.00,
    currency: 'usdc',
    multiplier: 0,
    payout: null,
    timestamp: Date.now() - 8000,
  },
];
